<?php

namespace App\Helpers;

final class Country
{
    /**
     * @return string[]
     */
    public static function default(): array
    {
        return [
            ["code" => "FR", "name" => "France", "name_fr" => "France"],
        ];
    }

    /**
     * @return string[]
     */
    public static function all(): array
    {
        return [
            ["code" => "AF", "name" => "Afghanistan", "name_fr" => "Afghanistan"],
            ["code" => "AL", "name" => "Albania", "name_fr" => "Albanie"],
            ["code" => "AQ", "name" => "Antarctica", "name_fr" => "Antarctique"],
            ["code" => "DZ", "name" => "Algeria", "name_fr" => "Algérie"],
            ["code" => "AS", "name" => "American Samoa", "name_fr" => "Samoa Américaines"],
            ["code" => "AD", "name" => "Andorra", "name_fr" => "Andorre"],
            ["code" => "AO", "name" => "Angola", "name_fr" => "Angola"],
            ["code" => "AG", "name" => "Antigua and Barbuda", "name_fr" => "Antigua-et-Barbuda"],
            ["code" => "AZ", "name" => "Azerbaijan", "name_fr" => "Azerbaïdjan"],
            ["code" => "AR", "name" => "Argentina", "name_fr" => "Argentine"],
            ["code" => "AU", "name" => "Australia", "name_fr" => "Australie"],
            ["code" => "AT", "name" => "Austria", "name_fr" => "Autriche"],
            ["code" => "BS", "name" => "Bahamas", "name_fr" => "Bahamas"],
            ["code" => "BH", "name" => "Bahrain", "name_fr" => "Bahreïn"],
            ["code" => "BD", "name" => "Bangladesh", "name_fr" => "Bangladesh"],
            ["code" => "AM", "name" => "Armenia", "name_fr" => "Arménie"],
            ["code" => "BB", "name" => "Barbados", "name_fr" => "Barbade"],
            ["code" => "BE", "name" => "Belgium", "name_fr" => "Belgique"],
            ["code" => "BM", "name" => "Bermuda", "name_fr" => "Bermudes"],
            ["code" => "BT", "name" => "Bhutan", "name_fr" => "Bhoutan"],
            ["code" => "BO", "name" => "Bolivia", "name_fr" => "Bolivie"],
            ["code" => "BA", "name" => "Bosnia and Herzegovina", "name_fr" => "Bosnie-Herzégovine"],
            ["code" => "BW", "name" => "Botswana", "name_fr" => "Botswana"],
            ["code" => "BV", "name" => "Bouvet Island", "name_fr" => "Île Bouvet"],
            ["code" => "BR", "name" => "Brazil", "name_fr" => "Brésil"],
            ["code" => "BZ", "name" => "Belize", "name_fr" => "Belize"],
            ["code" => "IO", "name" => "British Indian Ocean Territory", "name_fr" => "Territoire Britannique de l'Océan Indien"],
            ["code" => "SB", "name" => "Solomon Islands", "name_fr" => "Îles Salomon"],
            ["code" => "VG", "name" => "British Virgin Islands", "name_fr" => "Îles Vierges Britanniques"],
            ["code" => "BN", "name" => "Brunei Darussalam", "name_fr" => "Brunéi Darussalam"],
            ["code" => "BG", "name" => "Bulgaria", "name_fr" => "Bulgarie"],
            ["code" => "MM", "name" => "Myanmar", "name_fr" => "Myanmar"],
            ["code" => "BI", "name" => "Burundi", "name_fr" => "Burundi"],
            ["code" => "BY", "name" => "Belarus", "name_fr" => "Bélarus"],
            ["code" => "KH", "name" => "Cambodia", "name_fr" => "Cambodge"],
            ["code" => "CM", "name" => "Cameroon", "name_fr" => "Cameroun"],
            ["code" => "CA", "name" => "Canada", "name_fr" => "Canada"],
            ["code" => "CV", "name" => "Cape Verde", "name_fr" => "Cap-vert"],
            ["code" => "KY", "name" => "Cayman Islands", "name_fr" => "Îles Caïmanes"],
            ["code" => "CF", "name" => "Central African", "name_fr" => "République Centrafricaine"],
            ["code" => "LK", "name" => "Sri Lanka", "name_fr" => "Sri Lanka"],
            ["code" => "TD", "name" => "Chad", "name_fr" => "Tchad"],
            ["code" => "CL", "name" => "Chile", "name_fr" => "Chili"],
            ["code" => "CN", "name" => "China", "name_fr" => "Chine"],
            ["code" => "TW", "name" => "Taiwan", "name_fr" => "Taïwan"],
            ["code" => "CX", "name" => "Christmas Island", "name_fr" => "Île Christmas"],
            ["code" => "CC", "name" => "Cocos (Keeling) Islands", "name_fr" => "Îles Cocos (Keeling)"],
            ["code" => "CO", "name" => "Colombia", "name_fr" => "Colombie"],
            ["code" => "KM", "name" => "Comoros", "name_fr" => "Comores"],
            ["code" => "YT", "name" => "Mayotte", "name_fr" => "Mayotte"],
            ["code" => "CG", "name" => "Republic of the Congo", "name_fr" => "République du Congo"],
            ["code" => "CD", "name" => "The Democratic Republic Of The Congo", "name_fr" => "République Démocratique du Congo"],
            ["code" => "CK", "name" => "Cook Islands", "name_fr" => "Îles Cook"],
            ["code" => "CR", "name" => "Costa Rica", "name_fr" => "Costa Rica"],
            ["code" => "HR", "name" => "Croatia", "name_fr" => "Croatie"],
            ["code" => "CU", "name" => "Cuba", "name_fr" => "Cuba"],
            ["code" => "CY", "name" => "Cyprus", "name_fr" => "Chypre"],
            ["code" => "CZ", "name" => "Czech Republic", "name_fr" => "République Tchèque"],
            ["code" => "BJ", "name" => "Benin", "name_fr" => "Bénin"],
            ["code" => "DK", "name" => "Denmark", "name_fr" => "Danemark"],
            ["code" => "DM", "name" => "Dominica", "name_fr" => "Dominique"],
            ["code" => "DO", "name" => "Dominican Republic", "name_fr" => "République Dominicaine"],
            ["code" => "EC", "name" => "Ecuador", "name_fr" => "Équateur"],
            ["code" => "SV", "name" => "El Salvador", "name_fr" => "El Salvador"],
            ["code" => "GQ", "name" => "Equatorial Guinea", "name_fr" => "Guinée Équatoriale"],
            ["code" => "ET", "name" => "Ethiopia", "name_fr" => "Éthiopie"],
            ["code" => "ER", "name" => "Eritrea", "name_fr" => "Érythrée"],
            ["code" => "EE", "name" => "Estonia", "name_fr" => "Estonie"],
            ["code" => "FO", "name" => "Faroe Islands", "name_fr" => "Îles Féroé"],
            ["code" => "FK", "name" => "Falkland Islands", "name_fr" => "Îles (malvinas) Falkland"],
            ["code" => "GS", "name" => "South Georgia and the South Sandwich Islands", "name_fr" => "Géorgie du Sud et les Îles Sandwich du Sud"],
            ["code" => "FJ", "name" => "Fiji", "name_fr" => "Fidji"],
            ["code" => "FI", "name" => "Finland", "name_fr" => "Finlande"],
            ["code" => "AX", "name" => "Åland Islands", "name_fr" => "Îles Åland"],
            ["code" => "GF", "name" => "French Guiana", "name_fr" => "Guyane Française"],
            ["code" => "PF", "name" => "French Polynesia", "name_fr" => "Polynésie Française"],
            ["code" => "TF", "name" => "French Southern Territories", "name_fr" => "Terres Australes Françaises"],
            ["code" => "DJ", "name" => "Djibouti", "name_fr" => "Djibouti"],
            ["code" => "GA", "name" => "Gabon", "name_fr" => "Gabon"],
            ["code" => "GE", "name" => "Georgia", "name_fr" => "Géorgie"],
            ["code" => "GM", "name" => "Gambia", "name_fr" => "Gambie"],
            ["code" => "PS", "name" => "Occupied Palestinian Territory", "name_fr" => "Territoire Palestinien Occupé"],
            ["code" => "DE", "name" => "Germany", "name_fr" => "Allemagne"],
            ["code" => "GH", "name" => "Ghana", "name_fr" => "Ghana"],
            ["code" => "GI", "name" => "Gibraltar", "name_fr" => "Gibraltar"],
            ["code" => "KI", "name" => "Kiribati", "name_fr" => "Kiribati"],
            ["code" => "GR", "name" => "Greece", "name_fr" => "Grèce"],
            ["code" => "GL", "name" => "Greenland", "name_fr" => "Groenland"],
            ["code" => "GD", "name" => "Grenada", "name_fr" => "Grenade"],
            ["code" => "GP", "name" => "Guadeloupe", "name_fr" => "Guadeloupe"],
            ["code" => "GU", "name" => "Guam", "name_fr" => "Guam"],
            ["code" => "GT", "name" => "Guatemala", "name_fr" => "Guatemala"],
            ["code" => "GN", "name" => "Guinea", "name_fr" => "Guinée"],
            ["code" => "GY", "name" => "Guyana", "name_fr" => "Guyana"],
            ["code" => "HT", "name" => "Haiti", "name_fr" => "Haïti"],
            ["code" => "HM", "name" => "Heard Island and McDonald Islands", "name_fr" => "Îles Heard et Mcdonald"],
            ["code" => "VA", "name" => "Vatican City State", "name_fr" => "Saint-Siège (état de la Cité du Vatican)"],
            ["code" => "HN", "name" => "Honduras", "name_fr" => "Honduras"],
            ["code" => "HK", "name" => "Hong Kong", "name_fr" => "Hong-Kong"],
            ["code" => "HU", "name" => "Hungary", "name_fr" => "Hongrie"],
            ["code" => "IS", "name" => "Iceland", "name_fr" => "Islande"],
            ["code" => "IN", "name" => "India", "name_fr" => "Inde"],
            ["code" => "ID", "name" => "Indonesia", "name_fr" => "Indonésie"],
            ["code" => "IR", "name" => "Islamic Republic of Iran", "name_fr" => "République Islamique d'Iran"],
            ["code" => "IQ", "name" => "Iraq", "name_fr" => "Iraq"],
            ["code" => "IE", "name" => "Ireland", "name_fr" => "Irlande"],
            ["code" => "IL", "name" => "Israel", "name_fr" => "Israël"],
            ["code" => "IT", "name" => "Italy", "name_fr" => "Italie"],
            ["code" => "CI", "name" => "Côte d'Ivoire", "name_fr" => "Côte d'Ivoire"],
            ["code" => "JM", "name" => "Jamaica", "name_fr" => "Jamaïque"],
            ["code" => "JP", "name" => "Japan", "name_fr" => "Japon"],
            ["code" => "KZ", "name" => "Kazakhstan", "name_fr" => "Kazakhstan"],
            ["code" => "JO", "name" => "Jordan", "name_fr" => "Jordanie"],
            ["code" => "KE", "name" => "Kenya", "name_fr" => "Kenya"],
            ["code" => "KP", "name" => "Democratic People's Republic of Korea", "name_fr" => "République Populaire Démocratique de Corée"],
            ["code" => "KR", "name" => "Republic of Korea", "name_fr" => "République de Corée"],
            ["code" => "KW", "name" => "Kuwait", "name_fr" => "Koweït"],
            ["code" => "KG", "name" => "Kyrgyzstan", "name_fr" => "Kirghizistan"],
            ["code" => "LA", "name" => "Lao People's Democratic Republic", "name_fr" => "République Démocratique Populaire Lao"],
            ["code" => "LB", "name" => "Lebanon", "name_fr" => "Liban"],
            ["code" => "LS", "name" => "Lesotho", "name_fr" => "Lesotho"],
            ["code" => "LV", "name" => "Latvia", "name_fr" => "Lettonie"],
            ["code" => "LR", "name" => "Liberia", "name_fr" => "Libéria"],
            ["code" => "LY", "name" => "Libyan Arab Jamahiriya", "name_fr" => "Jamahiriya Arabe Libyenne"],
            ["code" => "LI", "name" => "Liechtenstein", "name_fr" => "Liechtenstein"],
            ["code" => "LT", "name" => "Lithuania", "name_fr" => "Lituanie"],
            ["code" => "LU", "name" => "Luxembourg", "name_fr" => "Luxembourg"],
            ["code" => "MO", "name" => "Macao", "name_fr" => "Macao"],
            ["code" => "MG", "name" => "Madagascar", "name_fr" => "Madagascar"],
            ["code" => "MW", "name" => "Malawi", "name_fr" => "Malawi"],
            ["code" => "MY", "name" => "Malaysia", "name_fr" => "Malaisie"],
            ["code" => "MV", "name" => "Maldives", "name_fr" => "Maldives"],
            ["code" => "ML", "name" => "Mali", "name_fr" => "Mali"],
            ["code" => "MT", "name" => "Malta", "name_fr" => "Malte"],
            ["code" => "MQ", "name" => "Martinique", "name_fr" => "Martinique"],
            ["code" => "MR", "name" => "Mauritania", "name_fr" => "Mauritanie"],
            ["code" => "MU", "name" => "Mauritius", "name_fr" => "Maurice"],
            ["code" => "MX", "name" => "Mexico", "name_fr" => "Mexique"],
            ["code" => "MN", "name" => "Mongolia", "name_fr" => "Mongolie"],
            ["code" => "MD", "name" => "Republic of Moldova", "name_fr" => "République de Moldova"],
            ["code" => "MS", "name" => "Montserrat", "name_fr" => "Montserrat"],
            ["code" => "MA", "name" => "Morocco", "name_fr" => "Maroc"],
            ["code" => "MZ", "name" => "Mozambique", "name_fr" => "Mozambique"],
            ["code" => "OM", "name" => "Oman", "name_fr" => "Oman"],
            ["code" => "NA", "name" => "Namibia", "name_fr" => "Namibie"],
            ["code" => "NR", "name" => "Nauru", "name_fr" => "Nauru"],
            ["code" => "NP", "name" => "Nepal", "name_fr" => "Népal"],
            ["code" => "NL", "name" => "Netherlands", "name_fr" => "Pays-Bas"],
            ["code" => "AN", "name" => "Netherlands Antilles", "name_fr" => "Antilles Néerlandaises"],
            ["code" => "AW", "name" => "Aruba", "name_fr" => "Aruba"],
            ["code" => "NC", "name" => "New Caledonia", "name_fr" => "Nouvelle-Calédonie"],
            ["code" => "VU", "name" => "Vanuatu", "name_fr" => "Vanuatu"],
            ["code" => "NZ", "name" => "New Zealand", "name_fr" => "Nouvelle-Zélande"],
            ["code" => "NI", "name" => "Nicaragua", "name_fr" => "Nicaragua"],
            ["code" => "NE", "name" => "Niger", "name_fr" => "Niger"],
            ["code" => "NG", "name" => "Nigeria", "name_fr" => "Nigéria"],
            ["code" => "NU", "name" => "Niue", "name_fr" => "Niué"],
            ["code" => "NF", "name" => "Norfolk Island", "name_fr" => "Île Norfolk"],
            ["code" => "NO", "name" => "Norway", "name_fr" => "Norvège"],
            ["code" => "MP", "name" => "Northern Mariana Islands", "name_fr" => "Îles Mariannes du Nord"],
            ["code" => "UM", "name" => "United States Minor Outlying Islands", "name_fr" => "Îles Mineures Éloignées des États-Unis"],
            ["code" => "FM", "name" => "Federated States of Micronesia", "name_fr" => "États Fédérés de Micronésie"],
            ["code" => "MH", "name" => "Marshall Islands", "name_fr" => "Îles Marshall"],
            ["code" => "PW", "name" => "Palau", "name_fr" => "Palaos"],
            ["code" => "PK", "name" => "Pakistan", "name_fr" => "Pakistan"],
            ["code" => "PA", "name" => "Panama", "name_fr" => "Panama"],
            ["code" => "PG", "name" => "Papua New Guinea", "name_fr" => "Papouasie-Nouvelle-Guinée"],
            ["code" => "PY", "name" => "Paraguay", "name_fr" => "Paraguay"],
            ["code" => "PE", "name" => "Peru", "name_fr" => "Pérou"],
            ["code" => "PH", "name" => "Philippines", "name_fr" => "Philippines"],
            ["code" => "PN", "name" => "Pitcairn", "name_fr" => "Pitcairn"],
            ["code" => "PL", "name" => "Poland", "name_fr" => "Pologne"],
            ["code" => "PT", "name" => "Portugal", "name_fr" => "Portugal"],
            ["code" => "GW", "name" => "Guinea-Bissau", "name_fr" => "Guinée-Bissau"],
            ["code" => "TL", "name" => "Timor-Leste", "name_fr" => "Timor-Leste"],
            ["code" => "PR", "name" => "Puerto Rico", "name_fr" => "Porto Rico"],
            ["code" => "QA", "name" => "Qatar", "name_fr" => "Qatar"],
            ["code" => "RE", "name" => "Réunion", "name_fr" => "Réunion"],
            ["code" => "RO", "name" => "Romania", "name_fr" => "Roumanie"],
            ["code" => "RU", "name" => "Russian Federation", "name_fr" => "Fédération de Russie"],
            ["code" => "RW", "name" => "Rwanda", "name_fr" => "Rwanda"],
            ["code" => "SH", "name" => "Saint Helena", "name_fr" => "Sainte-Hélène"],
            ["code" => "KN", "name" => "Saint Kitts and Nevis", "name_fr" => "Saint-Kitts-et-Nevis"],
            ["code" => "AI", "name" => "Anguilla", "name_fr" => "Anguilla"],
            ["code" => "LC", "name" => "Saint Lucia", "name_fr" => "Sainte-Lucie"],
            ["code" => "PM", "name" => "Saint-Pierre and Miquelon", "name_fr" => "Saint-Pierre-et-Miquelon"],
            ["code" => "VC", "name" => "Saint Vincent and the Grenadines", "name_fr" => "Saint-Vincent-et-les Grenadines"],
            ["code" => "SM", "name" => "San Marino", "name_fr" => "Saint-Marin"],
            ["code" => "ST", "name" => "Sao Tome and Principe", "name_fr" => "Sao Tomé-et-Principe"],
            ["code" => "SA", "name" => "Saudi Arabia", "name_fr" => "Arabie Saoudite"],
            ["code" => "SN", "name" => "Senegal", "name_fr" => "Sénégal"],
            ["code" => "SC", "name" => "Seychelles", "name_fr" => "Seychelles"],
            ["code" => "SL", "name" => "Sierra Leone", "name_fr" => "Sierra Leone"],
            ["code" => "SG", "name" => "Singapore", "name_fr" => "Singapour"],
            ["code" => "SK", "name" => "Slovakia", "name_fr" => "Slovaquie"],
            ["code" => "VN", "name" => "Vietnam", "name_fr" => "Viet Nam"],
            ["code" => "SI", "name" => "Slovenia", "name_fr" => "Slovénie"],
            ["code" => "SO", "name" => "Somalia", "name_fr" => "Somalie"],
            ["code" => "ZA", "name" => "South Africa", "name_fr" => "Afrique du Sud"],
            ["code" => "ZW", "name" => "Zimbabwe", "name_fr" => "Zimbabwe"],
            ["code" => "ES", "name" => "Spain", "name_fr" => "Espagne"],
            ["code" => "EH", "name" => "Western Sahara", "name_fr" => "Sahara Occidental"],
            ["code" => "SD", "name" => "Sudan", "name_fr" => "Soudan"],
            ["code" => "SR", "name" => "Suriname", "name_fr" => "Suriname"],
            ["code" => "SJ", "name" => "Svalbard and Jan Mayen", "name_fr" => "Svalbard etÎle Jan Mayen"],
            ["code" => "SZ", "name" => "Swaziland", "name_fr" => "Swaziland"],
            ["code" => "SE", "name" => "Sweden", "name_fr" => "Suède"],
            ["code" => "CH", "name" => "Switzerland", "name_fr" => "Suisse"],
            ["code" => "SY", "name" => "Syrian Arab Republic", "name_fr" => "République Arabe Syrienne"],
            ["code" => "TJ", "name" => "Tajikistan", "name_fr" => "Tadjikistan"],
            ["code" => "TH", "name" => "Thailand", "name_fr" => "Thaïlande"],
            ["code" => "TG", "name" => "Togo", "name_fr" => "Togo"],
            ["code" => "TK", "name" => "Tokelau", "name_fr" => "Tokelau"],
            ["code" => "TO", "name" => "Tonga", "name_fr" => "Tonga"],
            ["code" => "TT", "name" => "Trinidad and Tobago", "name_fr" => "Trinité-et-Tobago"],
            ["code" => "AE", "name" => "United Arab Emirates", "name_fr" => "Émirats Arabes Unis"],
            ["code" => "TN", "name" => "Tunisia", "name_fr" => "Tunisie"],
            ["code" => "TR", "name" => "Turkey", "name_fr" => "Turquie"],
            ["code" => "TM", "name" => "Turkmenistan", "name_fr" => "Turkménistan"],
            ["code" => "TC", "name" => "Turks and Caicos Islands", "name_fr" => "Îles Turks et Caïques"],
            ["code" => "TV", "name" => "Tuvalu", "name_fr" => "Tuvalu"],
            ["code" => "UG", "name" => "Uganda", "name_fr" => "Ouganda"],
            ["code" => "UA", "name" => "Ukraine", "name_fr" => "Ukraine"],
            ["code" => "MK", "name" => "The Former Yugoslav Republic of Macedonia", "name_fr" => "L'ex-République Yougoslave de Macédoine"],
            ["code" => "EG", "name" => "Egypt", "name_fr" => "Égypte"],
            ["code" => "GB", "name" => "United Kingdom", "name_fr" => "Royaume-Uni"],
            ["code" => "IM", "name" => "Isle of Man", "name_fr" => "Île de Man"],
            ["code" => "TZ", "name" => "United Republic Of Tanzania", "name_fr" => "République-Unie de Tanzanie"],
            ["code" => "US", "name" => "United States", "name_fr" => "États-Unis"],
            ["code" => "VI", "name" => "U.S. Virgin Islands", "name_fr" => "Îles Vierges des États-Unis"],
            ["code" => "BF", "name" => "Burkina Faso", "name_fr" => "Burkina Faso"],
            ["code" => "UY", "name" => "Uruguay", "name_fr" => "Uruguay"],
            ["code" => "UZ", "name" => "Uzbekistan", "name_fr" => "Ouzbékistan"],
            ["code" => "VE", "name" => "Venezuela", "name_fr" => "Venezuela"],
            ["code" => "WF", "name" => "Wallis and Futuna", "name_fr" => "Wallis et Futuna"],
            ["code" => "WS", "name" => "Samoa", "name_fr" => "Samoa"],
            ["code" => "YE", "name" => "Yemen", "name_fr" => "Yémen"],
            ["code" => "CS", "name" => "Serbia and Montenegro", "name_fr" => "Serbie-et-Monténégro"],
            ["code" => "ZM", "name" => "Zambia", "name_fr" => "Zambie"],
        ];
    }
}
